### ISSUE TITLE
couldn't find usage page

### ISSUE THREAD

**Issue by brianpenghe** [suhrig/pingpongpro#2]
Hi Sabastian,
I couldn't find usage page on the release page.
In the tar ball I downloaded, there's the .cpp file but it doesn't have any usage messages I guess?
Do you have an example showing how to run the compiled c++ script? 

Thanks

**Comment by suhrig** [comment]
Hi Brian,

The usage instructions can be found in the zip file [pingpongpro-v1.0.zip](https://github.com/suhrig/pingpongpro/releases/download/v1.0/pingpongpro-v1.0.zip) on the releases page. They are contained in the file `pingpongpro-v1.0-manual.pdf`, specifically in the section `command-line options`. Alternatively, you can run the tool with the option `-h` to get a list of accepted parameters. In the simplest case, you run the tool using the following command:

```
pingpongpro -i SAM_INPUT_FILE -o OUTPUT_DIRECTORY
```

If you want to find out which transposons are suppressed through the ping-pong cycle, you will also want to use the option `-t`.

Regards,
Sebastian

**Comment by brianpenghe** [comment]
Thanks Sebastian. Yes this one is clear! I was checking out an earlier version which didn't have the bin folder or the pdf file. But this version (1.0.2) is good! Thanks!
