### ISSUE TITLE
Stack height

### ISSUE THREAD

**Issue by SofiaZhangtj** [suhrig/pingpongpro#5]
[ping-pong_signature_z-scores.pdf](https://github.com/suhrig/pingpongpro/files/5369646/ping-pong_signature_z-scores.pdf)

Hi Suhrig,
I would like to consult how to calculated the stack height score in ping-pong_signature_z-scores.pdf ? It is related to the reads number?  Thank you.
Best regards,
Sofia

**Comment by suhrig** [comment]
Hi Sofia,

The stack height score is derived from the number of reads that make up a ping-pong signature. PingPongPro first identifies the highest stack in the sample and then divides this maximum in 1000 equal-sized bins. Actually, it uses the log10 of the stack heights, or else the bins at the low end would be overcrowded and bins at the higher end of the range would be sparsely filled. After all signatures have been assigned to a bin, empty bins are dropped. So usually, you end up with less than 1000 bins. The bin number assigned to a signature is the stack height score.

In your example, the signatures are assigned a score of 0, which means they are supported by just very few reads, such that the end up in the lowest bin.

Regards,
Sebastian

**Comment by SofiaZhangtj** [comment]
Hi Sebastian,
Thank you for your kind explanation. It becomes clear to me!
Best regards,
Sofia
